name:                Image-Compressor
version:             0.1.0.0
github:              "githubuser/Image-Compressor"
license:             BSD3
author:              "Quentin Camilleri"
maintainer:          "quentin.camilleri@epitech.eu"
copyright:           "2022 Quentin Camilleri"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Image-Compressor#readme>

dependencies:
- base >= 4.7 && < 5
- optparse-applicative
- random

library:
  source-dirs: src

executables:
  Image-Compressor-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Image-Compressor

tests:
  Image-Compressor-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Image-Compressor
    - optparse-applicative
    - random
